{{- include "okta.validateInputs" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "okta.serviceAccountName" . }}
  namespace: {{ include "okta.namespace" . }}
  annotations:
    azure.workload.identity/client-id: {{ include "okta.workloadIdentityClientId" . }}